### ISSUE TITLE
PowerUI not working with Unity 2021.3.22

### ISSUE THREAD

**Issue by kausikp11** [Kulestar/powerui#22]
Hi Team, I have imported the package to my working library. I was working the same way as mentioned but couldnt find the package imported. Also the Powerui Manager file is missing. Can you share me a install demo video or tutorial page please so that I can try and come back to you.

I am using Unity 2021.3.22 in Windows operating system.

**Comment by philfleck** [comment]
i use a modified version which works on UWP (Hololens2, Desktop), Android and iOs which you can find here

https://github.com/philfleck/ragrug/tree/master/arclient/ragrug_unity_2021/Assets

best p

**Comment by kausikp11** [comment]
Hi @philfleck I tried using your asset in my Unity, but it is showing the same like having compilation error. I am also trying to install the Unity version you have used. Will let you know if any update is there. 

If possible can you try using the asset in the Unity 2021.3.22f1.

Thank you for quick response.

#Update: Sorry I was opening the whole project.
Post copy pasting the powerui it was working well with few errors. Will share it if I cannot resolve it.

**Comment by philfleck** [comment]
for which platform are you trying to compile? .Net should be >4 and not 2.0 ... - i have not tried any standalone builds ...
